// from: https://github.com/vintage/party_flutter/blob/master/assets/data/categories_en.json
// TODO: use other data
export default [
  'Alligator',
  'Ant',
  'Bear',
  'Bee',
  'Bird',
  'Bug',
  'Bunny',
  'Camel',
  'Cat',
  'Cheetah',
  'Chicken',
  'Chimpanzee',
  'Chinchilla',
  'Clownfish',
  'Cow',
  'Crab',
  'Crocodile',
  'Deer',
  'Dog',
  'Dolphin',
  'Duck',
  'Eagle',
  'Elephant',
  'Fish',
  'Fly',
  'Fox',
  'Frog',
  'Giraffe',
  'Goat',
  'Goldfish',
  'Gorilla',
  'Guinea Pig',
  'Hamster',
  'Hedgehog',
  'Hermit crab',
  'Hippo',
  'Horse',
  'Human',
  'Jelly fish',
  'Kangaroo',
  'Killer whale',
  'Kitten',
  'Lamb',
  'Leopard',
  'Lion',
  'Lobster',
  'Lynx',
  'Manatee',
  'Meerkat',
  'Monkey',
  'Mule',
  'Octopus',
  'Otter',
  'Owl',
  'Ox',
  'Panda',
  'Parrot',
  'Peacock',
  'Penguin',
  'Pig',
  'Pigeon',
  'Platypus',
  'Polar Bear',
  'Puma',
  'Puppy',
  'Rabbit',
  'Raccoon',
  'Rat',
  'Red Panda',
  'Rhinoceros',
  'Rooster',
  'Scorpion',
  'Seahorse',
  'Seal',
  'Shark',
  'Sheep',
  'Shrimp',
  'Snail',
  'Snake',
  'Snow Leopard',
  'Spider',
  'Squid',
  'Squirrel',
  'Star fish',
  'Stingray',
  'Swan',
  'Tiger',
  'Turkey',
  'Turtle',
  'Walrus',
  'Whale',
  'Wolf',
  'Yak',
  'Zebra',
  'Zoo',
  '7 Up',
  'Acid',
  'Almond',
  'Apple',
  'Apple pie',
  'Bacon',
  'Bagel',
  'Banana',
  'Basil',
  'Bean',
  'Beer',
  'Berry',
  'Bite',
  'Bitter',
  'Bland',
  'Bounty',
  'Brandy',
  'Breakfast',
  'Broccoli',
  'Brownie',
  'Burger',
  'Burger King',
  'Burritos',
  'Butter',
  'Cabbage',
  'Caesar',
  'Cake',
  'Calamari',
  'Candy',
  'Celery',
  'Champagne',
  'Cheese',
  'Cheeseburger',
  'Cheesecake',
  'Chewing gum',
  'Chili',
  'Chips',
  'Chocolate',
  'Coca-Cola',
  'Coffee',
  'Cookie',
  'Corn',
  'Corn Flakes',
  'Cottage cheese',
  'Crunchy',
  'Cupcake',
  'Dinner',
  'Donut',
  'Dr. Pepper',
  'Eggs',
  'Fanta',
  'Fork',
  'French fries',
  'Fried chicken',
  'Garlic bread',
  'Ginger',
  'Herbs',
  'Hot dog',
  'Hot wings',
  'Ice cream',
  'Jelly',
  'KFC',
  'Kebab',
  'Lasagna',
  'Lemonade',
  'Lobster',
  'Lollipop',
  'Lunch',
  'Mac and cheese',
  'Margarine',
  "McDonald's",
  'Milk',
  'Mint',
  'Mountain Dew',
  'Mushroom',
  'Noodles',
  'Nougat',
  'Onion',
  'Oreo',
  'Pancakes',
  'Pasta',
  'Pepper',
  'Pepsi',
  'Pizza',
  'Pizza Hut',
  'Plate',
  'Popcorn',
  'Potato',
  'Quesadilla',
  'Raw',
  'Restaurant',
  'Ribs',
  'Rice',
  'Salty',
  'Sausage',
  'Shrimp',
  'Snacks',
  'Soup',
  'Sour',
  'Spaghetti',
  'Spicy',
  'Spoon',
  'Sprite',
  'Steak',
  'Subway',
  'Sugar',
  'Sushi',
  'Sweet',
  'Taco Bell',
  'Tacos',
  'Tea',
  'Toast',
  'Toffee',
  'Tuna',
  'Waffles',
  'Water',
  'Watermelon',
  "Wendy's",
  'White chocolate',
  'Yogurt',
  'Accountant',
  'Actor',
  'Allergist',
  'Babysitter',
  'Bailiff',
  'Barista',
  'Barman',
  'Beautician',
  'Bricklayer',
  'Broker',
  'Bus driver',
  'Cameraman',
  'Carpenter',
  'Cashier',
  'Clerk',
  'Confectioner',
  'Construction manager',
  'Consultant',
  'Cook',
  'Courier',
  'Credit advisor',
  'Critic',
  'Curator',
  'Dealer',
  'Debt collector',
  'Dentist',
  'Dermatologist',
  'Detective',
  'Diabetologist',
  'Digger operator',
  'Doctor',
  'Driver',
  'Driving instructor',
  'Electrician',
  'Estate agent',
  'Farmer',
  'Fireman',
  'Graphic designer',
  'Gravedigger',
  'Hairdresser',
  'Heart surgeon',
  'Hostess',
  'Insurance agent',
  'Insurance broker',
  'Interior architect',
  'Journalist',
  'Judge',
  'Lawyer',
  'Lecturer',
  'Librarian',
  'Locksmith',
  'Masseur',
  'Mechanic',
  'Merchant',
  'Midwife',
  'Model',
  'Motorman',
  'Notary',
  'Nurse',
  'Nutritionist',
  'Office worker',
  'Official',
  'Oncologist',
  'Ophthalmologist',
  'Optician',
  'Packer',
  'Paramedic',
  'Paver',
  'Personal trainer',
  'Photographer',
  'Physicist',
  'Pilot',
  'Plasterer',
  'Plumber',
  'Policeman',
  'Politician',
  'Postman',
  'President',
  'Priest',
  'Professional gamer',
  'Programmer',
  'Psychiatrist',
  'Psychologist',
  'Public DEfender',
  'Receptionist',
  'Resident',
  'Robber',
  'Roofer',
  'Secretary',
  'Shopkeeper',
  'Singer',
  'Social worker',
  'Soldier',
  'Speech therapist',
  'Stewardess',
  'Stylist',
  'Surveyor',
  'Tailor',
  'Tattoo artist',
  'Taxi driver',
  'Teacher',
  'Telemarketer',
  'Tester',
  'Thief',
  'Tiler',
  'Tinsmith',
  'Tourist guide',
  'Truck driver',
  'Turner',
  'Vet',
  'Waiter',
  '3D printer',
  'Advertising billboard',
  'Armor',
  'Backpack',
  'Balloon',
  'Bar of chocolate',
  'Bird feeder',
  'Birthday cake',
  'Board game',
  'Bonsai tree',
  'Bottle of wine',
  'Box',
  'Broken bike',
  'Broom',
  'Camera',
  'Car',
  'Chainsaw',
  'Christmas tree',
  'Coffin',
  'Computer',
  'Computer virus',
  'Concrete lion',
  'Cup',
  'Dice',
  'Doghouse',
  'Door',
  'Drawer for socks',
  "Driver's seat",
  'Electric blanket',
  'Electric guitar',
  'Encyclopedia',
  'Everlasting',
  'Extension cord',
  'Flag',
  'Flowerpot',
  'Food processor',
  'Fork',
  'Fountain pen',
  'Garden gnome',
  'Garden set',
  'Gas pump',
  'Gel pen',
  'Greeting card',
  'Gun',
  'Halberd',
  'Handcuffs',
  'Harmonica',
  'Healthy sandwich',
  'Hot pot',
  'Important letter',
  'Ink printer',
  'Iron',
  'Jack',
  'Jar',
  'Keyboard',
  'Knife',
  'Landline phone',
  'Leaf',
  'Leaky pontoon',
  'Light bulb',
  'Lipstick',
  'Magic wand',
  'Magnifying glass',
  'Medical marijuana',
  'Mixer',
  'Mobile phone',
  'Newspaper',
  'Notebook',
  'Old glasses',
  'Optical drive',
  'Painting',
  'Passenger seat',
  'Percussion',
  'Persian rug',
  'Piano',
  'Piggybank',
  'Plant',
  'Plate',
  'Plotter',
  'Plunger',
  'Portable console',
  'Pouch',
  'Primer',
  'Radiator',
  'Reel',
  'Rocket launcher',
  'Sand castle',
  'Sandpit',
  'Sarcophagus',
  'Sash',
  'Saucepan',
  'Sewing Machine',
  'Siphon',
  'Sniper rifle',
  'Sofa',
  'Spike heels',
  'Spoon',
  'Spork',
  'Strap',
  'Sugar Lamb',
  'Suit',
  'Suitcase on wheels',
  'Swing',
  'Swivel chair',
  'TV',
  'TV decoder',
  'Tabloid',
  'Tambourine',
  'Tea',
  'Telescope',
  'Tights',
  'Trampoline',
  'Trumpet',
  'Uniform',
  'Wall clock',
  'Warning triangle',
  'Washing grater',
  'Wedding dress',
  'Wet carpet',
  'Window',
  'ZIP code',
  'Airport',
  'Amusement park',
  'Aquarium',
  'Art gallery',
  'Bakery',
  'Balcony',
  'Bank',
  'Bar',
  'Beach',
  'Beauty salon',
  'Bedroom',
  'Bicycle store',
  'Bivouac',
  'Bookstore',
  'Botanical garden',
  'Bowling alley',
  'Bus station',
  'Bus stop',
  'Cafe',
  'Campground',
  'Car dealer',
  'Car rental',
  'Car wash',
  'Casino',
  'Castle',
  'Catacombs',
  'Cave',
  'Chocolate factory',
  'Church',
  'Cinema',
  'Clinic',
  'Construction shop',
  'Court',
  'Courthouse',
  'Den',
  'Dentist',
  'Desert',
  'Detroit',
  'Dunes',
  'Elevator',
  'Embassy',
  'Exercise yard',
  'Fire station',
  'Florist',
  'Forest',
  'Funeral home',
  'Furniture store',
  'Garbage dump',
  'Garden',
  'Graveyard',
  'Grocery store',
  'Gym',
  'Hair salon',
  'Harbor',
  'Home',
  'Hospital',
  'Insurance agency',
  'Jail',
  'Jewelry store',
  'Jungle',
  'Las Vegas',
  'Laundry',
  'Library',
  'Lighthouse',
  'Lodging',
  'London',
  'Los Angeles',
  'Manchester',
  'Mine',
  'Mosque',
  'Mountains',
  'Movie rental',
  'Museum',
  'National park',
  'New York',
  'Nightclub',
  'Office',
  'Old town',
  'Opera',
  'Orchard',
  'Park',
  'Parking',
  'Petrol station',
  'Pharmacy',
  'Platform',
  'Police station',
  'Post office',
  'Prison',
  'Pub',
  'Railway station',
  'Real estate agency',
  'Restaurant',
  'Roof',
  'Room',
  'Spa',
  'School',
  'Sea',
  'Shipyard',
  'Shoe store',
  'Shopping center',
  'Sports hall',
  'Subway station',
  'Supermarket',
  'Synagogue',
  'Taxi stand',
  'Temple',
  'Tennis court',
  'Theater',
  'Top of the mountain',
  'Town hall',
  'Train station',
  'Travel agency',
  'Underground',
  'Walmart',
  'Warehouse',
  'Wilderness',
  'Yellowstone National Park',
  'Zoo',
];
